/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'postId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'anime' : IDL.Null,
  'recipes' : IDL.Null,
  'other' : IDL.Null,
  'travel' : IDL.Null,
  'tech' : IDL.Null,
  'lifestyle' : IDL.Null,
  'health' : IDL.Null,
  'poetries' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'authorId' : IDL.Principal,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'likes' : IDL.Vec(IDL.Principal),
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'about' : IDL.Opt(IDL.Text), 'profilePicUrl' : IDL.Opt(IDL.Text) });
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'profile' : IDL.Opt(UserProfile),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommentToPost' : IDL.Func([Comment], [IDL.Nat], []),
  'addLikeToPost' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [BlogPost],
      [IDL.Record({ 'id' : IDL.Nat, 'createdAt' : IDL.Int })],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getPopularPosts' : IDL.Func([IDL.Nat], [IDL.Vec(BlogPost)], []),
  'getPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(BlogPost)], ['query']),
  'getUniqueAuthors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSample' : IDL.Func([], [], []),
  'setAdminRole' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'updatePost' : IDL.Func([IDL.Nat, BlogPost], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'postId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'anime' : IDL.Null,
    'recipes' : IDL.Null,
    'other' : IDL.Null,
    'travel' : IDL.Null,
    'tech' : IDL.Null,
    'lifestyle' : IDL.Null,
    'health' : IDL.Null,
  'poetries' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'authorId' : IDL.Principal,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'likes' : IDL.Vec(IDL.Principal),
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'about' : IDL.Opt(IDL.Text), 'profilePicUrl' : IDL.Opt(IDL.Text) });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'profile' : IDL.Opt(UserProfile),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommentToPost' : IDL.Func([Comment], [IDL.Nat], []),
    'addLikeToPost' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [BlogPost],
        [IDL.Record({ 'id' : IDL.Nat, 'createdAt' : IDL.Int })],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getPopularPosts' : IDL.Func([IDL.Nat], [IDL.Vec(BlogPost)], []),
    'getPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(BlogPost)], ['query']),
    'getUniqueAuthors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSample' : IDL.Func([], [], []),
    'setAdminRole' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'updatePost' : IDL.Func([IDL.Nat, BlogPost], [], []),
  });
};

export const init = ({ IDL }) => { return []; };