/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'coverImageUrl' : [] | [string],
  'title' : string,
  'likeCount' : bigint,
  'authorId' : Principal,
  'body' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'likes' : Array<Principal>,
  'category' : Category,
}
export type Category = { 'anime' : null } |
  { 'recipes' : null } |
  { 'other' : null } |
  { 'travel' : null } |
  { 'tech' : null } |
  { 'lifestyle' : null } |
  { 'health' : null } |
  { 'poetries' : null };
export interface Comment {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'postId' : bigint,
}
export interface UserInfo {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : [] | [UserProfile],
}
export interface UserProfile {
  'name' : string,
  'about' : [] | [string],
  'profilePicUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommentToPost' : ActorMethod<[Comment], bigint>,
  'addLikeToPost' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<
    [BlogPost],
    { 'id' : bigint, 'createdAt' : bigint }
  >,
  'deleteComment' : ActorMethod<[bigint, bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPost' : ActorMethod<[bigint], Array<Comment>>,
  'getPopularPosts' : ActorMethod<[bigint], Array<BlogPost>>,
  'getPostById' : ActorMethod<[bigint], BlogPost>,
  'getPostsByCategory' : ActorMethod<[Category], Array<BlogPost>>,
  'getUniqueAuthors' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<UserInfo>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSample' : ActorMethod<[], undefined>,
  'setAdminRole' : ActorMethod<[Principal, boolean], undefined>,
  'updatePost' : ActorMethod<[bigint, BlogPost], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
